### ISSUE TITLE
user-can-see-their-car.md

### ISSUE THREAD

**Issue by yadanur** [yadanur/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create index.html, styles.css, and main.js files
- [x] Set the background to green
- [x] Place an image of a race car
- [x] Resize the image such that image width is the 1/5 of the screen width
