### ISSUE TITLE
user-can-turn-their-car.md

### ISSUE THREAD

**Issue by yadanur** [yadanur/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a js file and link it with the html file
- [x] Define a function to rotate the image left
- [x] Define a function to rotate the image rigth
- [x] Link the turn functions to the keyboard events
